version: '3.1'
services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: onjin/alpine-postgres:13.0
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      LANG: 'en_US.UTF-8'
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgre_sql_data:/var/lib/postgresql/data

volumes:
  postgre_sql_data: